line1="Hey,{name} Here!".format(name="Vansh")
print(line1)
line2="My sid is {sid}".format(sid=22105053)
print(line2)
line3="I am from {dep} department amd my cgpa s{cgpa}".format(dep="ECE",cgpa=9.9)
print(line3)                               
